[programs.localnet]
smart_charging_and_blockchain = "BNZkLCaLHpA8M3kuGWk1saNYdAbrE8TKfZdCkBJbC2QR"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/ethan-stone/solana-wallets/cpo.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
